### ISSUE TITLE
Add option to hide login fields?

### ISSUE THREAD

**Issue by binaryfire** [arxeiss/Adminer-FillLoginForm#1]
Hi there,

Thanks, this is just what I was looking for. Would it be possible to add an option to hide specific login fields as well? 

I'd like to set the values for system, server, username and database and then hide those fields so only the password field is visible.

Cheers

**Comment by binaryfire** [comment]
Never mind :) I created a plugin which hides it via CSS, all good.

**Comment by arxeiss** [comment]
Hi, I would do probably the same.
